---
name: Build container image

on:
  pull_request:
    branches: ['*']

  schedule:
    - cron: '05 10 * * *' # 10:05 UTC daily

  push:
    branches: ['*']
    paths-ignore:
      - '**/README.md'
      - 'releases.json'

  workflow_dispatch:

env:
  IMAGE_DESC: "Zerith"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image

    runs-on: ubuntu-24.04

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        flavor:
          - ""
          - "nvidia"

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Change image name depending on build flavor
        env:
          BUILD_FLAVOR: ${{ matrix.flavor }}
        run: |
          if [ -n "$BUILD_FLAVOR" ]; then
            echo "IMAGE_NAME=${IMAGE_NAME}-${BUILD_FLAVOR}" >> "$GITHUB_ENV"
          fi

      - name: Lowercase image variables
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> "$GITHUB_ENV"
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> "$GITHUB_ENV"

      - name: Set tag prefix
        if: github.ref_name != 'main'
        run: |
          echo "TAG_PREFIX=${{ github.ref_name }}." >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Get current date
        id: date
        run: |
          echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"

      - name: Generate image metadata
        id: metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}

          tags: |
            type=raw,value=${{ env.TAG_PREFIX }}{{date 'YYYYMMDD'}}
            type=raw,value=${{ env.TAG_PREFIX }}${{ env.DEFAULT_TAG }}
            type=sha,enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=pr

          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.sha }}/README.md
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version={{date 'YYYYMMDD'}}

          sep-tags: " "

      - name: Prepare build args
        run: |
          cat > build_args.txt <<EOF
          IMAGE=${{ env.IMAGE_NAME }}
          FLAVOR=${{ matrix.flavor }}
          EOF

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          oci: false

      - name: Post-process image
        run: |
          set -e
          buildah unshare bash -c '
            buildah images

            ctr=$(buildah from containers-storage:${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_PREFIX }}${{ env.DEFAULT_TAG }})
            mnt=$(buildah mount "$ctr")

            for d in etc var home dev proc sys run tmp mnt; do
                rm -rf "$mnt/$d"
                mkdir -p "$mnt/$d"
            done
            chmod 1777 "$mnt/tmp"

            rm -rf "$mnt/root" "$mnt/srv"
            ln -s var/roothome "$mnt/root"
            ln -s var/srv      "$mnt/srv"

            buildah unmount "$ctr"
            buildah commit "$ctr" post-processed
            buildah rm "$ctr"

            for tag in ${{ steps.metadata.outputs.tags }}; do
              buildah tag post-processed "$tag"
            done
          '

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
