name: Test Zerith

on:
  pull_request:
    branches: ['*']

  push:
    branches: ['*']
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
      - 'releases.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pytest
      - run: python3 -m pytest tests/
